# Use the official MySQL image as the base
FROM mysql:latest

# Set the environment variables
ENV MYSQL_ROOT_PASSWORD=170694
ENV MYSQL_DATABASE=first_database

# Copy the initialization script into the Docker image
COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL default port
EXPOSE 3306
